name: Python Test Runner

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    container: 
      image: gabrielfalcao/python-poetry:3.9

    steps:
    - uses: actions/checkout@v2

    - name: Cache Poetry virtual environment
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/tripadvisor/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        cd tripadvisor
        poetry install

    - name: Run tests
      run: |
        cd tripadvisor
        poetry run pytest test.py
